package schema

import (
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/google/jsonschema-go/jsonschema"
	ralphconfig "github.com/shuymn/ralph/internal/config"
)

const (
	GeneratedComment = "Code generated by ralph schema generator. DO NOT EDIT."
	ArtifactPath     = "schemas/config.schema.json"
	artifactFileMode = os.FileMode(0o600)

	completionReviewConvergence = "review_convergence"
	completionRunTailMatch      = "tail_match"
	gitCommitModeTogether       = "together"
	stepOnFailContinue          = "continue"
	stepUsesAutoCommit          = "auto_commit"
)

var (
	errNotObject   = errors.New("is not an object")
	errKeyNotFound = errors.New("key not found")
)

type constraintPatch struct {
	name  string
	path  []string
	apply func(target map[string]any)
}

var runtimeConstraintPatches = []constraintPatch{
	{
		name: "version const",
		path: []string{"properties", "version"},
		apply: func(target map[string]any) {
			target["const"] = ralphconfig.SupportedVersion
		},
	},
	{
		name: "git.commit enum",
		path: []string{"properties", "git", "properties", "commit"},
		apply: func(target map[string]any) {
			setEnum(target, ralphconfig.DefaultGitCommitMode, gitCommitModeTogether)
		},
	},
	{
		name: "completion.run.strategy enum",
		path: []string{
			"properties",
			"completion",
			"properties",
			"run",
			"properties",
			"strategy",
		},
		apply: func(target map[string]any) {
			setEnum(target, completionRunTailMatch)
		},
	},
	{
		name: "completion.run.tail_lines minimum",
		path: []string{
			"properties",
			"completion",
			"properties",
			"run",
			"properties",
			"tail_lines",
		},
		apply: func(target map[string]any) {
			setMinimumOne(target)
		},
	},
	{
		name: "completion.review.strategy enum",
		path: []string{
			"properties",
			"completion",
			"properties",
			"review",
			"properties",
			"strategy",
		},
		apply: func(target map[string]any) {
			setEnum(target, completionReviewConvergence)
		},
	},
	{
		name: "completion.review.review_convergence.min_reviews minimum",
		path: []string{
			"properties",
			"completion",
			"properties",
			"review",
			"properties",
			"review_convergence",
			"properties",
			"min_reviews",
		},
		apply: func(target map[string]any) {
			setMinimumOne(target)
		},
	},
	{
		name: "completion.review.review_convergence.max_reviews minimum",
		path: []string{
			"properties",
			"completion",
			"properties",
			"review",
			"properties",
			"review_convergence",
			"properties",
			"max_reviews",
		},
		apply: func(target map[string]any) {
			setMinimumOne(target)
		},
	},
	{
		name: "completion.review.review_convergence.judge_every minimum",
		path: []string{
			"properties",
			"completion",
			"properties",
			"review",
			"properties",
			"review_convergence",
			"properties",
			"judge_every",
		},
		apply: func(target map[string]any) {
			setMinimumOne(target)
		},
	},
	{
		name: "completion.review.review_convergence.stable_rounds minimum",
		path: []string{
			"properties",
			"completion",
			"properties",
			"review",
			"properties",
			"review_convergence",
			"properties",
			"stable_rounds",
		},
		apply: func(target map[string]any) {
			setMinimumOne(target)
		},
	},
	{
		name: "pre.steps[].on_fail enum",
		path: []string{
			"properties",
			"phases",
			"properties",
			"pre",
			"properties",
			"steps",
			"items",
			"properties",
			"on_fail",
		},
		apply: func(target map[string]any) {
			setEnum(target, stepOnFailContinue, ralphconfig.DefaultStepOnFail)
		},
	},
	{
		name: "post.steps[].on_fail enum",
		path: []string{
			"properties",
			"phases",
			"properties",
			"post",
			"properties",
			"steps",
			"items",
			"properties",
			"on_fail",
		},
		apply: func(target map[string]any) {
			setEnum(target, stepOnFailContinue, ralphconfig.DefaultStepOnFail)
		},
	},
	{
		name: "pre.steps[].uses enum",
		path: []string{
			"properties",
			"phases",
			"properties",
			"pre",
			"properties",
			"steps",
			"items",
			"properties",
			"uses",
		},
		apply: func(target map[string]any) {
			setEnum(target, stepUsesAutoCommit)
		},
	},
	{
		name: "post.steps[].uses enum",
		path: []string{
			"properties",
			"phases",
			"properties",
			"post",
			"properties",
			"steps",
			"items",
			"properties",
			"uses",
		},
		apply: func(target map[string]any) {
			setEnum(target, stepUsesAutoCommit)
		},
	},
	{
		name: "pre.steps[] run/uses xor",
		path: []string{"properties", "phases", "properties", "pre", "properties", "steps", "items"},
		apply: func(target map[string]any) {
			setRunUsesXOR(target)
		},
	},
	{
		name: "post.steps[] run/uses xor",
		path: []string{
			"properties",
			"phases",
			"properties",
			"post",
			"properties",
			"steps",
			"items",
		},
		apply: func(target map[string]any) {
			setRunUsesXOR(target)
		},
	},
}

func Generate() ([]byte, error) {
	schemaDoc, err := jsonschema.For[ralphconfig.Config](nil)
	if err != nil {
		return nil, fmt.Errorf("infer config schema: %w", err)
	}
	schemaDoc.Comment = GeneratedComment

	rawSchema, err := json.Marshal(schemaDoc)
	if err != nil {
		return nil, fmt.Errorf("marshal inferred schema: %w", err)
	}

	var root map[string]any
	if err := json.Unmarshal(rawSchema, &root); err != nil {
		return nil, fmt.Errorf("decode inferred schema: %w", err)
	}

	if err := applyRuntimeConstraints(root); err != nil {
		return nil, fmt.Errorf("apply runtime constraints: %w", err)
	}

	output, err := json.MarshalIndent(root, "", "  ")
	if err != nil {
		return nil, fmt.Errorf("marshal schema: %w", err)
	}
	return append(output, '\n'), nil
}

func WriteRoot(root string) error {
	output, err := Generate()
	if err != nil {
		return fmt.Errorf("generate schema: %w", err)
	}
	path := filepath.Join(root, ArtifactPath)
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("create schema directory: %w", err)
	}
	if err := os.WriteFile(path, output, artifactFileMode); err != nil {
		return fmt.Errorf("write schema file %q: %w", path, err)
	}
	return nil
}

func applyRuntimeConstraints(root map[string]any) error {
	for _, patch := range runtimeConstraintPatches {
		target, err := objectAtPath(root, patch.path)
		if err != nil {
			return fmt.Errorf("%s: %w", patch.name, err)
		}
		patch.apply(target)
	}

	applyAdditionalPropertiesFalse(root)
	return nil
}

func objectAtPath(root map[string]any, path []string) (map[string]any, error) {
	current := any(root)
	for _, key := range path {
		node, ok := current.(map[string]any)
		if !ok {
			return nil, fmt.Errorf("segment %q: %w", key, errNotObject)
		}
		next, ok := node[key]
		if !ok {
			return nil, fmt.Errorf("missing key %q: %w", key, errKeyNotFound)
		}
		current = next
	}

	target, ok := current.(map[string]any)
	if !ok {
		return nil, fmt.Errorf("path %q: %w", strings.Join(path, "."), errNotObject)
	}
	return target, nil
}

func setEnum(target map[string]any, values ...string) {
	enum := make([]any, 0, len(values))
	for _, value := range values {
		enum = append(enum, value)
	}
	target["enum"] = enum
}

func setMinimumOne(target map[string]any) {
	target["minimum"] = 1
}

func setRunUsesXOR(target map[string]any) {
	target["oneOf"] = []any{
		map[string]any{
			"required": []any{"run"},
		},
		map[string]any{
			"required": []any{"uses"},
		},
	}
}

func applyAdditionalPropertiesFalse(node any) {
	schema, ok := node.(map[string]any)
	if !ok {
		return
	}

	if includesObjectType(schema["type"]) {
		schema["additionalProperties"] = false
	}

	if properties, ok := schema["properties"].(map[string]any); ok {
		for _, child := range properties {
			applyAdditionalPropertiesFalse(child)
		}
	}

	switch items := schema["items"].(type) {
	case map[string]any:
		applyAdditionalPropertiesFalse(items)
	case []any:
		for _, child := range items {
			applyAdditionalPropertiesFalse(child)
		}
	}

	for _, key := range []string{"oneOf", "anyOf", "allOf"} {
		options, ok := schema[key].([]any)
		if !ok {
			continue
		}
		for _, option := range options {
			applyAdditionalPropertiesFalse(option)
		}
	}
}

func includesObjectType(typeValue any) bool {
	switch typed := typeValue.(type) {
	case string:
		return typed == "object"
	case []any:
		for _, value := range typed {
			if typeName, ok := value.(string); ok && typeName == "object" {
				return true
			}
		}
	}
	return false
}
