package schema

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"

	"github.com/google/jsonschema-go/jsonschema"
	ralphconfig "github.com/shuymn/ralph/internal/config"
)

const (
	GeneratedComment = "Code generated by ralph schema generator. DO NOT EDIT."
	ArtifactPath     = "schemas/config.schema.json"
	artifactFileMode = os.FileMode(0o600)
)

func Generate() ([]byte, error) {
	schemaDoc, err := jsonschema.For[ralphconfig.Config](nil)
	if err != nil {
		return nil, fmt.Errorf("infer config schema: %w", err)
	}
	schemaDoc.Comment = GeneratedComment

	output, err := json.MarshalIndent(schemaDoc, "", "  ")
	if err != nil {
		return nil, fmt.Errorf("marshal schema: %w", err)
	}
	return append(output, '\n'), nil
}

func WriteRoot(root string) error {
	output, err := Generate()
	if err != nil {
		return fmt.Errorf("generate schema: %w", err)
	}
	path := filepath.Join(root, ArtifactPath)
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("create schema directory: %w", err)
	}
	if err := os.WriteFile(path, output, artifactFileMode); err != nil {
		return fmt.Errorf("write schema file %q: %w", path, err)
	}
	return nil
}
